"use client";

import { useState } from "react";
import {
  ArrowLeft, MapPin, Star, Users, DollarSign, ChevronRight,
  User, Car, TrendingUp, AlertTriangle, Briefcase, Clock,
  RefreshCw, Target, Sparkles, X, CheckCircle, Phone,
  Mail, MessageSquare, Crown, Activity
} from "lucide-react";
import { type Mission, type RetailerData, type CustomerProfile, type Region } from "@/lib/dashboard-data";
import { cn } from "@/lib/utils";

interface RetailerDrillDownProps {
  mission: Mission;
  region: Region;
  onBack: () => void;
}

const tierColors = {
  "Tier 1": { color: "#f59e0b", bg: "rgba(245,158,11,0.12)", border: "rgba(245,158,11,0.3)" },
  "Tier 2": { color: "#3b82f6", bg: "rgba(59,130,246,0.12)", border: "rgba(59,130,246,0.3)" },
  "Tier 3": { color: "#6b7280", bg: "rgba(107,114,128,0.12)", border: "rgba(107,114,128,0.3)" },
};

export function RetailerDrillDown({ mission, region, onBack }: RetailerDrillDownProps) {
  const [selectedRetailer, setSelectedRetailer] = useState<RetailerData | null>(null);
  const [selectedCustomer, setSelectedCustomer] = useState<CustomerProfile | null>(null);
  const [scriptGenerated, setScriptGenerated] = useState<string | null>(null);
  const [generatingScript, setGeneratingScript] = useState(false);

  const filteredRetailers = mission.retailers.filter(
    (r) => region === "Global" || r.region === region
  );

  const handleGenerateScript = (customer: CustomerProfile) => {
    setGeneratingScript(true);
    setTimeout(() => {
      setScriptGenerated(
        `BESPOKE CONCIERGE SCRIPT — ${customer.name} — ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}\n\n` +
        `OPENING:\n"Good [morning/afternoon], ${customer.name}. This is [RM Name] from ${selectedRetailer?.name}, calling on behalf of your dedicated JLR Private Client team. I'm reaching out because we've identified a very specific opportunity that I believe is exceptionally well-timed for you."\n\n` +
        `PERSONALISATION HOOK:\nReference: ${customer.currentVehicle} (${customer.currentVariant}) — equity position: ${customer.buybackEquity}\n\n` +
        `VALUE PROPOSITION:\n"Your current ${customer.currentVehicle} is performing exceptionally in today's market — our specialists have identified a ${customer.buybackEquity} equity advantage that, combined with our current Range Rover Electric priority allocation programme, creates a genuinely compelling financial case that may not be available beyond next quarter."\n\n` +
        `MISSION CONTEXT:\n${mission.title}\n"${mission.tagline}"\n\n` +
        `RECOMMENDED NEXT STEP:\n${customer.recommendedAction}\n\n` +
        `CONTACT PREFERENCE:\nBest window: ${customer.contactWindow}\nPreferred channel: ${customer.preferredChannel}\n\n` +
        `OBJECTION HANDLING:\n• If 'not the right time': "I completely understand. The equity position I mentioned is time-limited — our Q3 allocation closes 30 September. Would it help if I arranged a no-obligation private viewing at a time that suits?"\n• If 'happy with current vehicle': "That speaks to your excellent choice. This programme is specifically designed for our most valued clients who are already satisfied — it's about maximising the financial advantage your current vehicle has built."\n\nCLOSING:\n"Given your tenure of ${customer.tenure} with JLR, you'll have first access. I'll follow this up with a personalised proposal document — what email address should I use?"\n\n— Generated by Meridian Intelligence Engine v3.4`
      );
      setGeneratingScript(false);
    }, 1800);
  };

  return (
    <div className="space-y-5">
      {/* Breadcrumb Header */}
      <div className="flex items-center gap-3">
        <button
          onClick={onBack}
          className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-white/50 hover:text-white/80 hover:bg-white/[0.06] transition-all text-sm"
          style={{ border: "1px solid rgba(255,255,255,0.08)" }}
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Mission Command
        </button>
        <ChevronRight className="w-3.5 h-3.5 text-white/25" />
        <span className="text-white/60 text-sm font-medium">{mission.title}</span>
        <ChevronRight className="w-3.5 h-3.5 text-white/25" />
        <span className="text-white/40 text-sm">Retailer Intelligence</span>
      </div>

      {/* Mission Summary Strip */}
      <div className="flex items-center gap-4 p-4 rounded-2xl flex-wrap"
        style={{ background: `rgba(${hexToRgb(mission.color)}, 0.07)`, border: `1px solid rgba(${hexToRgb(mission.color)}, 0.22)` }}>
        <div className="w-8 h-8 rounded-xl flex items-center justify-center"
          style={{ background: `rgba(${hexToRgb(mission.color)}, 0.2)` }}>
          <Target className="w-4 h-4" style={{ color: mission.color }} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="text-white font-semibold text-sm font-heading truncate">{mission.title}</div>
          <div className="text-white/40 text-xs">"{mission.tagline}"</div>
        </div>
        <div className="flex gap-4 flex-shrink-0 flex-wrap">
          {[
            { label: "Revenue", value: mission.projectedRevenue[region] },
            { label: "Customers", value: mission.targetCustomers[region].toLocaleString() },
            { label: "Conv.", value: mission.conversionRate[region] },
          ].map((s) => (
            <div key={s.label} className="text-center">
              <div className="text-white font-bold text-sm font-heading">{s.value}</div>
              <div className="text-white/35 text-[10px]">{s.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Retailers Grid */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <div className="w-1 h-4 rounded-full bg-blue-500" />
            <h3 className="text-white font-semibold text-sm font-heading">
              {filteredRetailers.length} Retailers Mapped · {region}
            </h3>
          </div>
          <span className="text-white/40 text-xs">Ranked by mission fit score</span>
        </div>

        <div className="space-y-3">
          {filteredRetailers.map((retailer) => {
            const tc = tierColors[retailer.tier];
            const isExpanded = selectedRetailer?.id === retailer.id;

            return (
              <div key={retailer.id} className="rounded-2xl overflow-hidden transition-all duration-300"
                style={{
                  background: isExpanded ? "rgba(59,130,246,0.06)" : "rgba(255,255,255,0.04)",
                  border: isExpanded ? "1px solid rgba(59,130,246,0.3)" : "1px solid rgba(255,255,255,0.07)",
                }}>

                {/* Retailer Row */}
                <button
                  className="w-full flex items-center gap-4 p-4 hover:bg-white/[0.02] transition-all"
                  onClick={() => setSelectedRetailer(isExpanded ? null : retailer)}
                >
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                    style={{ background: "rgba(255,255,255,0.06)" }}>
                    <span className="text-white/60 text-sm font-bold">
                      {retailer.name.split(" ").map((w) => w[0]).join("").slice(0, 2)}
                    </span>
                  </div>

                  <div className="flex-1 text-left min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-white font-semibold text-sm">{retailer.name}</span>
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold"
                        style={{ background: tc.bg, border: `1px solid ${tc.border}`, color: tc.color }}>
                        {retailer.tier}
                      </span>
                    </div>
                    <div className="flex items-center gap-1 mt-0.5">
                      <MapPin className="w-2.5 h-2.5 text-white/30" />
                      <span className="text-white/40 text-xs">{retailer.location}</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-5 flex-shrink-0 flex-wrap justify-end">
                    <div className="text-right hidden sm:block">
                      <div className="text-white/60 text-[10px] mb-0.5">Mission Fit</div>
                      <div className="flex items-center gap-1">
                        <div className="w-20 h-1.5 rounded-full overflow-hidden" style={{ background: "rgba(255,255,255,0.08)" }}>
                          <div className="h-full rounded-full" style={{ width: `${retailer.missionFit}%`, background: "#3b82f6" }} />
                        </div>
                        <span className="text-blue-400 text-xs font-bold">{retailer.missionFit}%</span>
                      </div>
                    </div>
                    <div className="text-right hidden sm:block">
                      <div className="text-white/60 text-[10px] mb-0.5">Target Customers</div>
                      <div className="text-white font-bold text-sm">{retailer.targetCustomers}</div>
                    </div>
                    <div className="text-right hidden md:block">
                      <div className="text-white/60 text-[10px] mb-0.5">Proj. Revenue</div>
                      <div className="text-green-400 font-bold text-sm">{retailer.projectedRevenue}</div>
                    </div>
                    <ChevronRight className={cn(
                      "w-4 h-4 text-white/30 transition-transform duration-200",
                      isExpanded && "rotate-90"
                    )} />
                  </div>
                </button>

                {/* Expanded Customers */}
                {isExpanded && (
                  <div className="border-t border-white/[0.06] p-4">
                    <div className="flex items-center gap-2 mb-3">
                      <Users className="w-3.5 h-3.5 text-white/40" />
                      <span className="text-white/50 text-xs font-medium uppercase tracking-wider">
                        {retailer.customers.length} Perfect-Fit Customers
                      </span>
                    </div>
                    <div className="space-y-2">
                      {retailer.customers.map((customer) => (
                        <CustomerRow
                          key={customer.id}
                          customer={customer}
                          missionColor={mission.color}
                          onClick={() => setSelectedCustomer(customer)}
                        />
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Customer Profile Modal */}
      {selectedCustomer && selectedRetailer && (
        <CustomerModal
          customer={selectedCustomer}
          retailer={selectedRetailer}
          mission={mission}
          scriptGenerated={scriptGenerated}
          generatingScript={generatingScript}
          onGenerateScript={() => handleGenerateScript(selectedCustomer)}
          onClose={() => { setSelectedCustomer(null); setScriptGenerated(null); }}
        />
      )}
    </div>
  );
}

// ─── Customer Row ─────────────────────────────────────────────────────────────

function CustomerRow({ customer, missionColor, onClick }: {
  customer: CustomerProfile;
  missionColor: string;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className="w-full flex items-center gap-3 p-3 rounded-xl text-left hover:bg-white/[0.04] transition-all group"
      style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)" }}
    >
      <div className="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 font-bold text-xs"
        style={{ background: `rgba(${hexToRgb(missionColor)}, 0.2)`, color: missionColor }}>
        {customer.name.split(" ").map((n) => n[0]).join("")}
      </div>
      <div className="flex-1 min-w-0">
        <div className="text-white text-sm font-medium">{customer.name}</div>
        <div className="text-white/40 text-[10px]">{customer.currentVehicle} · {customer.location}</div>
      </div>
      <div className="hidden sm:flex items-center gap-3 flex-shrink-0 flex-wrap justify-end">
        <div className="text-right">
          <div className="text-[9px] text-white/30">Equity</div>
          <div className="text-green-400 text-xs font-bold">{customer.buybackEquity}</div>
        </div>
        <div className="text-right">
          <div className="text-[9px] text-white/30">Renewal Score</div>
          <div className="text-white text-xs font-bold">{customer.renewalScore}</div>
        </div>
        <div className="text-right">
          <div className="text-[9px] text-white/30">Lead Score</div>
          <div className="text-blue-400 text-xs font-bold">{customer.leadScore}</div>
        </div>
      </div>
      <ChevronRight className="w-3.5 h-3.5 text-white/25 group-hover:text-white/60 transition-colors flex-shrink-0" />
    </button>
  );
}

// ─── Customer Modal ───────────────────────────────────────────────────────────

interface CustomerModalProps {
  customer: CustomerProfile;
  retailer: RetailerData;
  mission: Mission;
  scriptGenerated: string | null;
  generatingScript: boolean;
  onGenerateScript: () => void;
  onClose: () => void;
}

function CustomerModal({ customer, retailer, mission, scriptGenerated, generatingScript, onGenerateScript, onClose }: CustomerModalProps) {
  const [scriptView, setScriptView] = useState(false);

  const scores = [
    { label: "Lead Score", value: customer.leadScore, max: 1, color: "#3b82f6" },
    { label: "Renewal Score", value: customer.renewalScore, max: 1, color: "#10b981" },
    { label: "Upsell Score", value: customer.upsellScore, max: 1, color: "#8b5cf6" },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "rgba(0,0,0,0.75)", backdropFilter: "blur(8px)" }}>
      <div className="w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-2xl flex flex-col"
        style={{ background: "rgba(8, 11, 20, 0.98)", border: "1px solid rgba(255,255,255,0.1)" }}>

        {/* Header */}
        <div className="flex items-start justify-between p-6 border-b border-white/[0.06]">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-full flex items-center justify-center font-bold text-base"
              style={{ background: `rgba(${hexToRgb(mission.color)}, 0.2)`, color: mission.color }}>
              {customer.name.split(" ").map((n) => n[0]).join("")}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="font-heading text-white font-bold text-base">{customer.name}</h2>
                <div className="flex items-center gap-1 px-1.5 py-0.5 rounded-full"
                  style={{ background: "rgba(245,158,11,0.15)", border: "1px solid rgba(245,158,11,0.3)" }}>
                  <Crown className="w-2.5 h-2.5 text-yellow-400" />
                  <span className="text-yellow-400 text-[9px] font-bold">PERFECT FIT</span>
                </div>
              </div>
              <div className="text-white/40 text-xs mt-0.5">{customer.career} · {customer.location}</div>
              <div className="text-white/30 text-[10px]">{retailer.name}</div>
            </div>
          </div>
          <button onClick={onClose} className="w-8 h-8 rounded-lg flex items-center justify-center text-white/40 hover:text-white hover:bg-white/[0.08] transition-all flex-shrink-0">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 scrollbar-thin space-y-5">
          {!scriptView ? (
            <>
              {/* Vehicle + Scores */}
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 rounded-xl space-y-2"
                  style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.07)" }}>
                  <div className="flex items-center gap-2 mb-2">
                    <Car className="w-3.5 h-3.5 text-white/40" />
                    <span className="text-white/40 text-[10px] uppercase tracking-wider">Current Vehicle</span>
                  </div>
                  <div className="text-white font-semibold text-sm">{customer.currentVehicle}</div>
                  <div className="text-white/50 text-xs">{customer.currentVariant}</div>
                  <div className="flex items-center gap-1.5 mt-2">
                    <DollarSign className="w-3 h-3 text-green-400" />
                    <span className="text-green-400 text-xs font-bold">{customer.buybackEquity} equity</span>
                  </div>
                </div>

                <div className="p-4 rounded-xl"
                  style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.07)" }}>
                  <div className="flex items-center gap-2 mb-3">
                    <Activity className="w-3.5 h-3.5 text-white/40" />
                    <span className="text-white/40 text-[10px] uppercase tracking-wider">AI Scores</span>
                  </div>
                  <div className="space-y-2.5">
                    {scores.map((score) => (
                      <div key={score.label}>
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-white/50 text-[10px]">{score.label}</span>
                          <span className="text-xs font-bold" style={{ color: score.color }}>{score.value}</span>
                        </div>
                        <div className="h-1 rounded-full" style={{ background: "rgba(255,255,255,0.08)" }}>
                          <div className="h-full rounded-full transition-all" style={{ width: `${score.value * 100}%`, background: score.color }} />
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Profile Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                  { label: "Tenure", value: customer.tenure, icon: Clock },
                  { label: "Lifetime Value", value: customer.lifetimeValue, icon: DollarSign },
                  { label: "Churn Risk", value: customer.cancellationRisk, icon: AlertTriangle },
                  { label: "Career", value: customer.career.split(" ").slice(0, 2).join(" "), icon: Briefcase },
                ].map((item) => (
                  <div key={item.label} className="p-3 rounded-xl text-center"
                    style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.07)" }}>
                    <item.icon className="w-3.5 h-3.5 mx-auto mb-1.5 text-white/30" />
                    <div className="text-[9px] text-white/35 uppercase tracking-wider mb-0.5">{item.label}</div>
                    <div className="text-white text-xs font-semibold leading-tight">{item.value}</div>
                  </div>
                ))}
              </div>

              {/* Mission Fit Reason */}
              <div className="p-4 rounded-xl"
                style={{ background: `rgba(${hexToRgb(mission.color)}, 0.07)`, border: `1px solid rgba(${hexToRgb(mission.color)}, 0.22)` }}>
                <div className="flex items-center gap-2 mb-2">
                  <Target className="w-3.5 h-3.5" style={{ color: mission.color }} />
                  <span className="text-xs font-semibold uppercase tracking-wider" style={{ color: mission.color }}>Why Perfect Fit</span>
                </div>
                <p className="text-white/65 text-sm leading-relaxed">{customer.missionFitReason}</p>
              </div>

              {/* Recommended Action */}
              <div className="p-4 rounded-xl"
                style={{ background: "rgba(59,130,246,0.07)", border: "1px solid rgba(59,130,246,0.22)" }}>
                <div className="flex items-center gap-2 mb-2">
                  <Sparkles className="w-3.5 h-3.5 text-blue-400" />
                  <span className="text-blue-400 text-xs font-semibold uppercase tracking-wider">Recommended Action</span>
                </div>
                <p className="text-white/70 text-sm leading-relaxed">{customer.recommendedAction}</p>
                <div className="flex flex-wrap gap-3 mt-3 text-xs text-white/40">
                  <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{customer.contactWindow}</span>
                  <span className="flex items-center gap-1"><MessageSquare className="w-3 h-3" />{customer.preferredChannel}</span>
                </div>
              </div>

              {/* Contact Actions */}
              <div className="grid grid-cols-3 gap-3">
                {[
                  { icon: Phone, label: "Call", color: "#10b981" },
                  { icon: Mail, label: "Email", color: "#3b82f6" },
                  { icon: MessageSquare, label: "Message", color: "#8b5cf6" },
                ].map((action) => (
                  <button key={action.label}
                    className="flex items-center justify-center gap-2 py-2.5 rounded-xl text-sm font-medium transition-all hover:scale-[1.02]"
                    style={{ background: `rgba(${hexToRgb(action.color)}, 0.12)`, border: `1px solid rgba(${hexToRgb(action.color)}, 0.3)`, color: action.color }}>
                    <action.icon className="w-3.5 h-3.5" />
                    {action.label}
                  </button>
                ))}
              </div>
            </>
          ) : (
            /* Script View */
            <div>
              <div className="flex items-center gap-2 mb-4">
                <CheckCircle className="w-4 h-4 text-green-400" />
                <span className="text-green-400 text-sm font-semibold">Bespoke Concierge Script Generated</span>
              </div>
              <div className="p-4 rounded-xl overflow-y-auto max-h-80 scrollbar-thin"
                style={{ background: "rgba(0,0,0,0.5)", border: "1px solid rgba(255,255,255,0.08)" }}>
                <pre className="text-white/70 text-xs leading-relaxed whitespace-pre-wrap font-mono">
                  {scriptGenerated}
                </pre>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-5 border-t border-white/[0.06] flex gap-3">
          {!scriptView ? (
            <>
              <button
                onClick={onGenerateScript}
                disabled={generatingScript}
                className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl font-semibold text-sm text-white transition-all hover:scale-[1.01]"
                style={{
                  background: generatingScript
                    ? "rgba(59,130,246,0.2)"
                    : "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
                  boxShadow: generatingScript ? "none" : "0 0 20px rgba(59,130,246,0.3)",
                }}
              >
                {generatingScript ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    Generating Script...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    Generate Bespoke Concierge Script
                  </>
                )}
              </button>
              {scriptGenerated && !generatingScript && (
                <button
                  onClick={() => setScriptView(true)}
                  className="px-4 py-3 rounded-xl text-sm font-semibold text-green-400 transition-all hover:bg-green-400/10"
                  style={{ border: "1px solid rgba(16,185,129,0.3)" }}>
                  View Script
                </button>
              )}
            </>
          ) : (
            <button
              onClick={() => setScriptView(false)}
              className="flex-1 py-3 rounded-xl text-sm font-semibold text-white/60 hover:text-white hover:bg-white/[0.06] transition-all"
              style={{ border: "1px solid rgba(255,255,255,0.1)" }}>
              Back to Profile
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

function hexToRgb(hex: string): string {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`
    : "59, 130, 246";
}
